apiVersion: apps/v1
kind: Deployment
metadata:
  name: vle9-healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vle9-healthcare
  template:
    metadata:
      labels:
        app: vle9-healthcare
    spec:
      serviceAccountName: vle9-healthcare-sa
      containers:
        - name: healthcare-app
          image: vle9-healthcare:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
